name: Create Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to tag (e.g., 1.2.3 or v1.2.3)'
        required: true
        type: string

jobs:
  create-tag:
    uses: mconf/mconf-ci-jobs/.github/workflows/all-create-tag.yml@main
    with:
      # version (required): Version to tag (e.g., 1.2.3 or v1.2.3)
      version: ${{ inputs.version }}
      # tag_prefix (optional): Prefix for the tag (default: v)
      # annotation_prefix (optional): Prefix for the tag annotation message (default: Version)
    secrets: inherit
