name: Build and Push Harbor Images

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    uses: mconf/mconf-ci-jobs/.github/workflows/all-build-push-image.yml@main
    with:
      # image_name (required): Name of the Docker image
      image_name: my-app
      # organization (required): Harbor organization name
      organization: my-organization
      # registry (required): Docker registry URL
      registry: registry.example.com
      # dockerfile_path (optional): Path to Dockerfile (default: ./Dockerfile)
      # platforms (optional): Target platforms (default: linux/amd64)
      # runs-on (optional): Runner to use (default: ["self-hosted", "ubuntu-22.04"])
    secrets: inherit
    # Required secrets:
    # HARBOR_USERNAME: Harbor registry username
    # HARBOR_PASSWORD: Harbor registry password
    # Optional secrets (for DockerHub authentication - login skipped if either is unset):
    # DOCKERHUB_USERNAME: DockerHub username
    # DOCKERHUB_PASSWORD: DockerHub password
