name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    uses: mconf/mconf-ci-jobs/.github/workflows/lb-go-tests.yml@main
    with:
      # go-version (required): Go version to use
      go-version: "1.21"
    secrets: inherit

