name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    uses: mconf/mconf-ci-jobs/.github/workflows/lb-node-build.yml@main
    with:
      # node-version (required): Node.js version
      node-version: '20'
