name: CI - Scan

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  scan_ruby:
    uses: mconf/mconf-ci-jobs/.github/workflows/portal-ruby-scan.yml@main
    # No inputs required - uses .ruby-version file from repository
    secrets: inherit
